# Generated by Django 3.0.5 on 2020-04-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200429_2329'),
        ('users', '0003_auto_20200417_1830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProjectAlerts',
            new_name='UserProjectAlert',
        ),
    ]
