# Generated by Django 4.1 on 2022-08-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_analytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="options",
            field=models.JSONField(default={}),
        ),
    ]
