# Generated by Django 4.1.3 on 2022-12-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_squashed_0008_alter_user_id_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
