# Generated by Django 4.2.5 on 2023-10-02 14:31
import os
from django.db import migrations


def add_OIDC_settings_from_env(apps, schema_editor):
    SocialApp = apps.get_model("socialaccount", "SocialApp")
    oidc_app_id = os.environ.get("SOCIALACCOUNT_PROVIDERS_openid_connect_SERVERS_0_id")
    oidc_app_server_url = os.environ.get(
        "SOCIALACCOUNT_PROVIDERS_openid_connect_SERVERS_0_server_url"
    )
    if oidc_app_id and oidc_app_server_url:
        db_social_app = SocialApp.objects.filter(provider=oidc_app_id).first()
        if db_social_app and not db_social_app.settings:
            db_social_app.provider = "openid_connect"
            db_social_app.provider_id = oidc_app_id
            db_social_app.settings = {"server_url": oidc_app_server_url}
            db_social_app.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_created"),
    ]

    operations = [
        migrations.RunPython(
            code=add_OIDC_settings_from_env, reverse_code=migrations.RunPython.noop
        )
    ]
