# Generated by Django 4.1.3 on 2022-11-29 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_alter_project_id_alter_projectcounter_id_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE users_userprojectalert RENAME TO projects_userprojectalert;",
            "ALTER TABLE projects_userprojectalert RENAME TO users_userprojectalert;",
        )
    ]
