# Generated by Django 4.2.5 on 2023-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_transactioneventprojecthourlystatistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
