# Generated by Django 4.2.5 on 2023-10-12 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_transactioneventprojecthourlystatistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="event_throttle_rate",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Probability (in percent) on how many events are throttled. Used for throttling at project level",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
