# Generated by Django 4.2.6 on 2023-10-17 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_project_event_throttle_rate"),
        ("projects", "0012_project_is_deleted"),
    ]

    operations = []
