# Generated by Django 3.1.4 on 2020-12-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_squashed_0010_auto_20210117_1543"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="issue",
            field=models.ForeignKey(
                help_text="Sentry calls this a group",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.issue",
            ),
        ),
    ]
