# Generated by Django 3.1.5 on 2021-01-16 21:10

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20201229_1643"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="tags",),
        HStoreExtension(),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.DeleteModel(name="EventTag",),
        migrations.DeleteModel(name="EventTagKey",),
        migrations.RunSQL(
            sql="DROP FUNCTION IF EXISTS add_event_tags;",
            reverse_sql="DROP FUNCTION IF EXISTS add_event_tags;",
        ),
    ]
