# Generated by Django 3.1.7 on 2021-02-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20210219_1931'),
        ('events', '0002_auto_20210122_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'sample'), (1, 'debug'), (2, 'info'), (3, 'warning'), (4, 'error'), (5, 'fatal')], default=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='issue',
            field=models.ForeignKey(default=1, help_text='Sentry calls this a group', on_delete=django.db.models.deletion.CASCADE, to='issues.issue'),
            preserve_default=False,
        ),
    ]
