# Generated by Django 3.2.7 on 2021-10-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0004_auto_20210509_1658'),
        ('projects', '0008_alter_projectkey_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugInformationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='debuginformationfile',
            index=models.Index(fields=['project', 'file'], name='difs_debugi_project_99cec2_idx'),
        ),
    ]
