# Generated by Django 4.1.3 on 2022-11-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_tokens", "0004_alter_apitoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
