# Generated by Django 3.1.4 on 2020-12-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentproject',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
