# Generated by Django 3.0 on 2019-12-06 03:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20191204_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(default=[(0, 'default'), (1, 'error'), (2, 'csp')], verbose_name=[(0, 'default'), (1, 'error'), (2, 'csp')])),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.PositiveSmallIntegerField(default=0, verbose_name=[(0, 'unresolved'), (1, 'resolved'), (2, 'ignored')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('level', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('sdk', django.contrib.postgres.fields.jsonb.JSONField()),
                ('release', models.CharField(max_length=255)),
                ('breadcrumbs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('request', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue')),
            ],
        ),
    ]
