# Generated by Django 3.0 on 2019-12-11 04:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('contexts', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('culprit', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(blank=True, help_text='Date created as claimed by client it came from', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entries', django.contrib.postgres.fields.jsonb.JSONField()),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('packages', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('platform', models.CharField(max_length=255)),
                ('sdk', django.contrib.postgres.fields.jsonb.JSONField()),
                ('title', models.CharField(max_length=255)),
                ('user', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('has_seen', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'sample'), (1, 'debug'), (2, 'info'), (3, 'warning'), (4, 'error'), (5, 'fatal')], default=0)),
                ('title', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'default'), (1, 'error'), (2, 'csp')], default=0)),
                ('culprit', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'unresolved'), (1, 'resolved'), (2, 'ignored')], default=0)),
            ],
        ),
    ]
