# Generated by Django 3.0.3 on 2020-03-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('title', 'culprit', 'project', 'type')},
        ),
    ]
