# Generated by Django 3.0.8 on 2020-07-14 13:33

from django.db import migrations, models
from .sql.triggers import INCREMENT_PROJECT_COUNTER_TRIGGER


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projectcounter"),
        ("issues", "0001_squashed_0004_auto_20200612_0027"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="short_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={
                ("project", "short_id"),
                ("title", "culprit", "project", "type"),
            },
        ),
        migrations.RunSQL(
            sql=INCREMENT_PROJECT_COUNTER_TRIGGER,
            reverse_sql="DROP TRIGGER IF EXISTS increment_project_counter on issues_issue; DROP FUNCTION IF EXISTS increment_project_counter;",
        ),
    ]
