# Generated by Django 3.2 on 2021-04-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0002_auto_20210219_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
