# Generated by Django 3.0 on 2019-12-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20191201_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
