# Generated by Django 3.0.8 on 2020-07-31 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20200714_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTagKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='issues.EventTag'),
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.EventTagKey'),
        ),
        migrations.AlterUniqueTogether(
            name='eventtag',
            unique_together={('key', 'value')},
        ),
    ]
