# Generated by Django 3.0.8 on 2020-08-04 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_auto_20200731_1531"),
    ]

    operations = []
