# Generated by Django 3.0.1 on 2020-01-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20200119_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='Date created as claimed by client it came from', null=True),
        ),
    ]
