# Generated by Django 3.2.8 on 2021-10-09 23:02

import collections
from django.db import migrations, models
from .sql.triggers import UPDATE_ISSUE_TRIGGER
from .sql.functions import GENERATE_ISSUE_TSVECTOR


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0004_alter_issue_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="tags",
            field=models.JSONField(default=dict),
        ),
        migrations.RunSQL(UPDATE_ISSUE_TRIGGER, UPDATE_ISSUE_TRIGGER),
        migrations.RunSQL(GENERATE_ISSUE_TSVECTOR, GENERATE_ISSUE_TSVECTOR),
    ]
