# Generated by Django 4.0.1 on 2022-01-20 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_tags'),
    ]

    operations = [
    ]
