# Generated by Django 3.1.2 on 2020-10-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20200805_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
