# Generated by Django 4.0.6 on 2022-07-15 20:48

from django.db import migrations
from .sql.functions import UPDATE_ISSUE_INDEX


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_auto_20220120_0040"),
    ]

    operations = [migrations.RunSQL(UPDATE_ISSUE_INDEX)]
