# Generated by Django 3.1.4 on 2020-12-27 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_auto_20201227_1518'),
        ('issues', '0007_auto_20201113_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='releases.release'),
        ),
    ]
