# Generated by Django 4.1.3 on 2022-11-14 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0007_auto_20220715_2048"),
    ]

    operations = []
