# Generated by Django 4.1.3 on 2022-11-14 20:29

from django.db import migrations
from .sql.functions import UPDATE_ISSUE_INDEX


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0007_auto_20220715_2048"),
    ]

    operations = [migrations.RunSQL(UPDATE_ISSUE_INDEX)]
