# Generated by Django 4.1.3 on 2022-11-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0008_auto_20221114_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
