# Generated by Django 3.1.4 on 2020-12-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20201229_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTag',
        ),
        migrations.DeleteModel(
            name='EventTagKey',
        ),
    ]
