# Generated by Django 4.1.3 on 2022-12-02 01:10

from django.db import migrations
from .sql.functions import JSONB_RECURSIVE_MERGE


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0009_alter_issue_id"),
    ]

    operations = [migrations.RunSQL(JSONB_RECURSIVE_MERGE)]
