# Generated by Django 4.2.2 on 2023-07-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_transactioneventprojecthourlystatistic"),
        ("issues", "0012_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={("project", "short_id")},
        ),
        migrations.CreateModel(
            name="IssueHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.UUIDField(db_index=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="issues.issue"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="issuehash",
            constraint=models.UniqueConstraint(
                fields=("project", "value"), name="project hash"
            ),
        ),
    ]
