# Generated by Django 4.1.3 on 2022-12-12 21:45

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    replaces = [
        ("projects", "0001_initial"),
        ("projects", "0002_auto_20200429_2329"),
        ("projects", "0003_projectcounter"),
        ("projects", "0004_auto_20200805_0107"),
        ("projects", "0005_project_first_event"),
        ("projects", "0006_project_scrub_ip_addresses"),
        ("projects", "0007_auto_20201026_2354"),
        ("projects", "0008_alter_projectkey_created"),
        ("projects", "0009_alter_project_id_alter_projectcounter_id_and_more"),
        ("projects", "0010_rename_useralert"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations_ext", "0001_squashed_0009_organization_scrub_ip_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from=["name", "organization_id"],
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("platform", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="organizations_ext.organization",
                    ),
                ),
                ("first_event", models.DateTimeField(null=True)),
                (
                    "scrub_ip_addresses",
                    models.BooleanField(
                        default=True, help_text="Should project anonymize IP Addresses"
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ProjectCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=64)),
                (
                    "public_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "rate_limit_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rate_limit_window",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProjectAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(choices=[(0, "off"), (1, "on")]),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "project")},
            },
        ),
    ]
