# Generated by Django 3.0 on 2019-12-15 15:50

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectkey',
            old_name='date_added',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='project',
            name='platform',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name', 'organization_id']),
        ),
    ]
