# Generated by Django 3.1 on 2020-08-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectkey',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
