# Generated by Django 3.1 on 2020-08-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200805_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='first_event',
            field=models.DateTimeField(null=True),
        ),
    ]
