# Generated by Django 3.1.2 on 2020-10-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_first_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scrub_ip_addresses',
            field=models.BooleanField(default=True, help_text='Should project scrub IP Addresses such as 192.168.*.* instead of full address'),
        ),
    ]
