# Generated by Django 4.2.5 on 2023-10-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_transactioneventprojecthourlystatistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="events_chance",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Probability (0 - 1) on how many events are accepted. Used for throttling at project level",
                max_digits=3,
            ),
        ),
    ]
