# Generated by Django 3.0.6 on 2020-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_ext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_accepting_events',
            field=models.BooleanField(default=True),
        ),
    ]
