# Generated by Django 3.0.6 on 2020-05-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_ext', '0002_organization_is_accepting_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_accepting_events',
            field=models.BooleanField(default=True, help_text='Used for throttling at org level'),
        ),
    ]
