# Generated by Django 3.0.6 on 2020-05-17 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_ext', '0003_auto_20200516_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='throttling_cycle_anchor',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Useful for organization level throttling or free tier usage plans'),
        ),
    ]
