# Generated by Django 3.0.7 on 2020-06-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_ext', '0005_remove_organization_throttling_cycle_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='open_membership',
            field=models.BooleanField(default=True, help_text='Allow any organization member to join any team'),
        ),
    ]
