# Generated by Django 3.0.7 on 2020-06-19 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations_ext', '0006_organization_open_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for pending invite', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations_ext_organizationuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together={('email', 'organization'), ('user', 'organization')},
        ),
    ]
