# Generated by Django 3.0.8 on 2020-07-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_ext', '0007_auto_20200619_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationuser',
            name='pending',
        ),
    ]
