# Generated by Django 3.1 on 2020-08-12 19:15
from django.db import migrations


def assign_org_user_to_org_owner(apps, schema_editor):
    """
    For some reason this didn't work. But I figure it doesn't matter; the
    role will be `3` when we run this
    """
    # OrganizationUserRole = apps.get_model("organizations_ext", "OrganizationUserRole")
    Organization = apps.get_model("organizations_ext", "Organization")

    """
    If there is an organization_user with the "owner" role and the org has no organization_owner,
    then make the (first) organization_user the organization owner.

    If necessary, could pick the first org user regardless of role, but I don't think it's necessary.

    If there's no org user at all, then there's almost certainly not a subscription either,
    so it shouldn't need to be dealt with
    """
    for org in Organization.objects.all():
        role = 3 # OrganizationUserRole.OWNER
        org_user_owners = org._org_user_model.objects.filter(
            organization=org.id, role=3
        )
        org_owner_count = org._org_owner_model.objects.filter(
            organization=org.id
        ).count()

        if org_owner_count == 0 and org_user_owners:
            org._org_owner_model.objects.create(
                organization=org.id, organization_user=org_user_owners.first()
            )
            org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_ext', '0008_remove_organizationuser_pending'),
    ]

    operations = [
        migrations.RunPython(assign_org_user_to_org_owner)
    ]
