# Generated by Django 4.1.4 on 2023-01-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uptime", "0003_auto_20211127_0159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="expected_status",
            field=models.PositiveSmallIntegerField(blank=True, default=200, null=True),
        ),
    ]
