# Generated by Django 4.2.1 on 2023-05-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uptime", "0006_alter_monitorcheck_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorcheck",
            name="is_change",
            field=models.BooleanField(
                default=False,
                help_text="Indicates change to is_up status for associated monitor",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="monitorcheck",
            index=models.Index(
                fields=["monitor", "-start_check"],
                name="uptime_moni_monitor_a89b32_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitorcheck",
            index=models.Index(
                fields=["monitor", "is_change", "-start_check"],
                name="uptime_moni_monitor_b6d442_idx",
            ),
        ),
    ]
