# Generated by Django 4.2.2 on 2023-06-09 15:40

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("organizations_ext", "0004_organizationsubscription_alter_organization_slug"),
        ("uptime", "0007_monitorcheck_is_change_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        populate_from=["name"],
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        help_text="When true, the status page URL is publicly accessible"
                    ),
                ),
                ("monitors", models.ManyToManyField(blank=True, to="uptime.monitor")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations_ext.organization",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="statuspage",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_organization_slug"
            ),
        ),
    ]
