# Generated by Django 3.1.5 on 2021-01-24 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_auto_20201026_2354'),
        ('performance', '0002_auto_20210124_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', models.JSONField(help_text='General event data that is searchable')),
                ('timestamp', models.DateTimeField(blank=True, help_text='Date created as claimed by client it came from', null=True)),
                ('transaction', models.CharField(max_length=1024)),
                ('start_timestamp', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
