# Generated by Django 4.0.3 on 2022-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_remove_transactionevent_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='span',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
