# Generated by Django 4.1.7 on 2023-03-31 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uptime", "0004_alter_monitor_expected_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="timeout",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Blank implies default value",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(28),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
