# Generated by Django 3.0.3 on 2020-04-17 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20200225_0247"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="subscribe_by_default",
            field=models.BooleanField(
                default=True,
                help_text="Subscribe to project notifications by default. Overrides project settings",
            ),
        ),
    ]
