# Generated by Django 4.0.1 on 2022-01-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alertrecipient_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectalert',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectalert',
            name='uptime',
            field=models.BooleanField(default=False, help_text='Send alert on any uptime monitor check failure'),
        ),
    ]
