# Generated by Django 4.1.3 on 2022-11-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0006_projectalert_name_projectalert_uptime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrecipient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projectalert",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
