# Generated by Django 4.2.2 on 2023-06-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "alerts",
            "0001_squashed_0007_alter_alertrecipient_id_alter_notification_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrecipient",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("webhook", "General Slack-compatible webhook"),
                    ("discord", "Discord"),
                ],
                max_length=16,
            ),
        ),
    ]
