# Generated by Django 4.2.1 on 2023-05-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "alerts",
            "0001_squashed_0007_alter_alertrecipient_id_alter_notification_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrecipient",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("discord", "Discord"),
                    ("webhook", "General Webhook"),
                    ("microsoft_teams", "Microsoft Teams"),
                    ("rocket_chat", "Rocket.Chat"),
                    ("slack", "Slack"),
                ],
                max_length=16,
            ),
        ),
    ]
