global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

rule_files:
  - "django.rules"

scrape_configs:
  - job_name: "glitchtip-backend"
    static_configs:
      - targets: ["web:8000"]
    metrics_path: /api/0/observability/django/
    authorization:
      credentials: enter-auth-token-here
