# Generated by Django 4.2.2 on 2023-06-09 13:45

from django.db import migrations
import apps.organizations_ext.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations_ext",
            "0001_squashed_0003_alter_organization_id_alter_organization_users_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSubscription",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("organizations_ext.organization",),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=apps.organizations_ext.fields.OrganizationSlugField(
                blank=True,
                editable=False,
                help_text="The name in all lowercase, suitable for URL identification",
                max_length=200,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
