# Generated by Django 4.0.2 on 2022-02-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_type_fileblobindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
