# Generated by Django 4.1.3 on 2022-12-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_squashed_0007_remove_file_blobs_file_blob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="type",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="fileblob",
            name="blob",
            field=models.FileField(upload_to="uploads/file_blobs"),
        ),
    ]
