# Generated by Django 3.0.8 on 2020-07-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issues", "0001_squashed_0010_auto_20210117_1543"),
        ("projects", "0003_projectcounter"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("comments", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "issue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issues.Issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                    ),
                ),
            ],
            options={"unique_together": {("project", "event_id")},},
        ),
    ]
